Update documentation for MKDocs
pnp/generator-teams pull request #244
Opened 2021-10-05 20:14 UTC by RickVanRousselt

Linked issue [#238]
This will be a V1 because certain things will have to be updated (tutorials, user guides, analytics,...)  afterwards.
But let's first setup the deployment of the docs

2021-10-06 06:16 UTC, wictorwilen requested changes
Awesome work!

2021-10-06 06:16 UTC, wictorwilen commented on docs/docs/contributing/getting-started.md
> +* [Node.js documentation](https://nodejs.org/dist/latest-v8.x/docs/api/) -
Should link to node LTS and not 8.x (since that is not supported anymore)

2021-10-11 09:36 UTC, RickVanRousselt commented on docs/docs/contributing/getting-started.md
> +* [Node.js documentation](https://nodejs.org/dist/latest-v8.x/docs/api/) -
Changed to the general Node docs page. That way we don't need to update this page every time the LTS version changes ;-)

2021-10-12 06:31 UTC, wictorwilen approved these changes
Good to go!

2021-10-12 06:31 UTC, merged