Rebuild bot implementation - Solves #237 & #246
pnp/generator-teams pull request #257
Opened 2021-10-25 19:03 UTC by stephanbisser

I rebuilt the bot implementation so that it aligns more with the official botbuilder samples and it allows devs to extend it with their dialogs quite easily.
Additionally, we can use this new template to add SSO functionality in the future as well, with little effort.
It should solve #237  and #246

2021-10-26 06:51 UTC, wictorwilen requested changes
See review comments.

2021-10-26 06:51 UTC, wictorwilen commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
Why rewriting this as *inline* code? This already exists in `express-msteams-host`. There are benefits and drawbacks of doing this: 

### Benefits

- As a dev you get all code and have full control and insights on what's happening
- More similar to the bot Fx samples

### Drawbacks

- The `BotDeclaration` attribute is less code
- We risk to loose the ability to upgrade code as we can't rely on the user not editing this file
- We loose the current implementation of Messaging Extensions (where they are separated from the actual bot implementation)

In any case, if we decide to do this update, then we probably should do that in a major version. And in such case we should also re-evaluate the other declarations used (connectors, webhooks etc)

2021-10-26 06:51 UTC, wictorwilen commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +                case "who" :
Perhaps we should also add the who & mention to the manifest bot commands?

2021-10-26 06:51 UTC, wictorwilen commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +export class MainDialog extends ComponentDialog {
`MainDialog` should be prefixed with the Bot name - in the case where you have multiple bots in your project

2021-10-26 06:51 UTC, wictorwilen commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +export class MainDialog extends ComponentDialog {
However, this dialog is in it's own sub-folder, specific to this bot...so I'm not sure...let's discuss?

2021-10-26 19:04 UTC, stephanbisser commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
Sorry @wictorwilen I didn't fully check the express-msteams-host. In that case you are completely right that we should stick with the BotDeclaration. We at least would need all the other code I added to the server.ts like adding the dialogs and stuff to make the template work flawlessly

2021-10-26 19:04 UTC, stephanbisser commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +                case "who" :
Absolutely yes!

2021-10-26 19:06 UTC, stephanbisser commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +export class MainDialog extends ComponentDialog {
I guess we do not need to add the bot name as a prefix but it would definitely help devs in terms of readability as it would take out the confusion if you are developing a multibot solution, so I think we could definitely add the bot's name as a prefix to the mainDialog

2021-10-26 19:08 UTC, stephanbisser commented
Thanks for the comments, I added my thoughts. In any case I'd like to make all tests green as well as changing the obvious things you mentioned before we continue 👍🏻

2021-10-26 20:38 UTC, wictorwilen commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
I can't see any dialogs in `server.ts` only in the bot folder. The only thing that I can see is missing is

- UserState - which we could add just as we do with conversation state
- a hook for a custom error handler

Let me take a look at that in the router package.

2021-10-27 06:27 UTC, stephanbisser commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
No the dialogs aren't in there you are right, but the bot which is then needed to attach the dialogs in `{botClassName}.ts` & `dialogBot.ts` (sorry for the confusion, I had thought I added the dialogs in the server.ts directly as I had seen that in some sample of the BotFx as well but didn't do it then it seems 😂)

2021-10-27 06:45 UTC, wictorwilen commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +export class MainDialog extends ComponentDialog {
The easiest way to update the `express-msteams-host` is to use the `BotDeclaration` `storage` parameter, which is used for the conversation state, to create an instance of the user state (how often do user and conversation state use different storage mechanisms?)

2021-10-27 06:52 UTC, stephanbisser commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
If we could get the `UserState` into the router package, then I could completely remove the bot declaration in the `server.ts` which would be great!

2021-10-27 06:58 UTC, wictorwilen commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
*Working on it*

2021-10-27 07:10 UTC, wictorwilen commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
Version `1.9.0-preview` will not instantiate classes with the `BotDeclaration` decorator with the following constructor arguments:  `(ConversationState, UserState, BotFrameworkAdapter)`

2021-10-27 08:19 UTC, stephanbisser commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +export class MainDialog extends ComponentDialog {
> (how often do user and conversation state use different storage mechanisms?)

Actually I guess in 0 cases you would like to use a different storage for both so we could update the `express-msteams-host` and should be good to go

2021-10-27 11:14 UTC, stephanbisser commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
Tested it with version 1.9.0-preview and it works as exptected. Updated my fork as well, so we should be good to go

2021-10-27 11:26 UTC, wictorwilen commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
I'll take it for a spin as well

2021-10-27 13:01 UTC, stephanbisser commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/mainDialog.ts
> +                case "who" :
That's now also part of my fork, so we then have all 3 commands in the manifest...

2021-10-27 13:11 UTC, andrewconnell commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/helpDialog.ts
> +        const message = MessageFactory.text(`I'm terribly sorry, but my developer hasn't trained me to do anything yet 😂. Please refer to [this link](https://docs.microsoft.com/en-us/microsoftteams/p
Super minor, but I'd remove `en-us/` from the URL (and all URLs to docs.msft.com). The docs will route the user to the correct locale based on their request. 

*yes, I've been working on docs a lot lately and this has been a sticking point for a while :)*

2021-10-27 14:36 UTC, stephanbisser commented on packages/generator-teams/src/bot/templates/src/server/{botName}/dialogs/helpDialog.ts
> +        const message = MessageFactory.text(`I'm terribly sorry, but my developer hasn't trained me to do anything yet 😂. Please refer to [this link](https://docs.microsoft.com/en-us/microsoftteams/p
done, thanks for the hint!

2021-10-29 11:38 UTC, stephanbisser commented on packages/generator-teams/src/app/templates/src/server/server.ts
> +<% if (botid) { %>
Did you already have time to test it out @wictorwilen?

2021-11-04 14:02 UTC, wictorwilen requested changes
Looks good and tests are working fine.
However the linting fails when scaffolding a bot - when those linting issues are cleaned up we can merge it into a preview

2021-11-04 14:25 UTC, stephanbisser commented
Let me work on that asap so that linting issues are resolved

2021-11-05 18:13 UTC, stephanbisser commented
Linting errors should be all fixed now, so we are good to go I guess

2021-11-08 13:19 UTC, merged